import { NextRequest, NextResponse } from "next/server";
import { ConvexHttpClient } from "convex/browser";
import { api } from "@/convex/_generated/api";
import { Id } from "@/convex/_generated/dataModel";

// Initialize Convex client for server-side operations
const convex = new ConvexHttpClient(process.env.NEXT_PUBLIC_CONVEX_URL!);

// Type definitions for the API request
interface TranscriptMessage {
  role: "agent" | "user";
  response: string;
  timestamp?: string;
  confidence?: number;
}

interface PublishTranscriptRequest {
  callId: string; // Convex ID of the call
  transcript: TranscriptMessage[];
  fullTranscript?: string;
  language?: string;
  duration?: number;
  createdAt?: string;
}

export async function POST(request: NextRequest) {
  console.log("[TRANSCRIPTS API] POST request received");
  
  try {
    console.log("[TRANSCRIPTS API] Parsing request body...");
    // Parse the request body
    const body: PublishTranscriptRequest = await request.json();
    console.log("[TRANSCRIPTS API] Request body parsed successfully:", JSON.stringify(body, null, 2));

    console.log("[TRANSCRIPTS API] Starting validation...");
    // Validate required fields
    if (!body.callId) {
      console.log("[TRANSCRIPTS API] Validation failed: Missing callId");
      return NextResponse.json(
        { error: "Missing required field: callId" },
        { status: 400 }
      );
    }
    console.log("[TRANSCRIPTS API] callId validation passed:", body.callId);

    if (!body.transcript || !Array.isArray(body.transcript)) {
      return NextResponse.json(
        { error: "Missing or invalid transcript array" },
        { status: 400 }
      );
    }

    console.log("[TRANSCRIPTS API] Validating transcript messages...");
    // Validate transcript messages
    for (let i = 0; i < body.transcript.length; i++) {
      const message = body.transcript[i];
      console.log(`[TRANSCRIPTS API] Validating message ${i + 1}:`, message);
      if (!message.role || !["agent", "user"].includes(message.role)) {
        console.log(`[TRANSCRIPTS API] Validation failed: Invalid role in message ${i + 1}:`, message.role);
        return NextResponse.json(
          { error: "Invalid transcript message: role must be 'agent' or 'user'" },
          { status: 400 }
        );
      }
      if (!message.response) {
        console.log(`[TRANSCRIPTS API] Validation failed: Missing response in message ${i + 1}`);
        return NextResponse.json(
          { error: "Invalid transcript message: response is required" },
          { status: 400 }
        );
      }
    }
    console.log("[TRANSCRIPTS API] All transcript messages validated successfully");

    // Verify the call exists
    console.log("[TRANSCRIPTS API] Verifying call exists...");
    const callId = body.callId as Id<"calls">;
    console.log("[TRANSCRIPTS API] Querying calls from Convex...");
    const existingCall = await convex.query(api.tasks.getCalls, {}).then(calls => {
      console.log("[TRANSCRIPTS API] Retrieved", calls.length, "calls from Convex");
      return calls.find(call => call._id === callId);
    });

    if (!existingCall) {
      console.log("[TRANSCRIPTS API] Call not found for callId:", callId);
      return NextResponse.json(
        { error: "Call not found" },
        { status: 404 }
      );
    }
    console.log("[TRANSCRIPTS API] Call found:", existingCall._id);

    // Check if transcript already exists
    console.log("[TRANSCRIPTS API] Checking if transcript already exists...");
    const existingTranscript = await convex.query(api.tasks.getTranscriptByCall, { callId });

    if (existingTranscript) {
      console.log("[TRANSCRIPTS API] Transcript already exists for call:", callId);
      return NextResponse.json(
        { error: "Transcript already exists for this call" },
        { status: 409 }
      );
    }
    console.log("[TRANSCRIPTS API] No existing transcript found, proceeding...");

    console.log("[TRANSCRIPTS API] Preparing transcript data...");
    // Prepare transcript data
    const transcriptData = {
      callId,
      transcript: body.transcript,
      fullTranscript: body.fullTranscript || body.transcript.map(msg => `${msg.role}: ${msg.response}`).join('\n'),
      language: body.language || "en",
      duration: body.duration || existingCall.duration,
      // Note: createdAt is auto-generated by Convex schema, not passed from request
    };
    console.log("[TRANSCRIPTS API] Transcript data prepared:", JSON.stringify(transcriptData, null, 2));

    console.log("[TRANSCRIPTS API] Saving transcript to Convex...");
    // Save transcript to Convex
    const transcriptId = await convex.mutation(api.tasks.addTranscript, transcriptData);
    console.log("[TRANSCRIPTS API] Transcript saved successfully with ID:", transcriptId);

    console.log("[TRANSCRIPTS API] Updating call transcript status...");
    // Update call to mark it has transcript and set status
    await convex.mutation(api.tasks.updateTranscriptStatus, {
      callId,
      status: "completed"
    });
    console.log("[TRANSCRIPTS API] Call transcript status updated to completed");

    console.log("[TRANSCRIPTS API] Syncing call flags...");
    // Sync call flags to update hasTranscript
    await convex.mutation(api.tasks.syncCallFlags, {});
    console.log("[TRANSCRIPTS API] Call flags synced successfully");

    return NextResponse.json({
      success: true,
      transcriptId,
      message: "Transcript published successfully"
    }, { status: 201 });

  } catch (error) {
    console.error("[TRANSCRIPTS API] Error publishing transcript:", error);
    console.error("[TRANSCRIPTS API] Error stack:", error instanceof Error ? error.stack : 'No stack trace');
    console.error("[TRANSCRIPTS API] Error name:", error instanceof Error ? error.name : 'Unknown');
    console.error("[TRANSCRIPTS API] Error message:", error instanceof Error ? error.message : String(error));
    
    if (error instanceof SyntaxError) {
      console.log("[TRANSCRIPTS API] Returning 400 - Invalid JSON");
      return NextResponse.json(
        { error: "Invalid JSON in request body" },
        { status: 400 }
      );
    }

    console.log("[TRANSCRIPTS API] Returning 500 - Internal server error");
    return NextResponse.json(
      { error: "Internal server error", details: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    );
  }
}

// GET method to retrieve transcript by call ID
export async function GET(request: NextRequest) {
  console.log("[TRANSCRIPTS API] GET request received");
  
  try {
    console.log("[TRANSCRIPTS API] Parsing URL search parameters...");
    const { searchParams } = new URL(request.url);
    console.log("[TRANSCRIPTS API] Search parameters:", Object.fromEntries(searchParams.entries()));
    const callId = searchParams.get("callId");
    console.log("[TRANSCRIPTS API] Extracted callId:", callId);

    if (!callId) {
      console.log("[TRANSCRIPTS API] Missing callId parameter");
      return NextResponse.json(
        { error: "Missing callId parameter" },
        { status: 400 }
      );
    }

    console.log("[TRANSCRIPTS API] Querying transcript from Convex for callId:", callId);
    const transcript = await convex.query(api.tasks.getTranscriptByCall, { 
      callId: callId as Id<"calls"> 
    });

    if (!transcript) {
      console.log("[TRANSCRIPTS API] Transcript not found for callId:", callId);
      return NextResponse.json(
        { error: "Transcript not found" },
        { status: 404 }
      );
    }
    console.log("[TRANSCRIPTS API] Transcript found, returning data");

    return NextResponse.json({
      success: true,
      transcript
    });

  } catch (error) {
    console.error("[TRANSCRIPTS API] Error retrieving transcript:", error);
    console.error("[TRANSCRIPTS API] Error stack:", error instanceof Error ? error.stack : 'No stack trace');
    console.error("[TRANSCRIPTS API] Error name:", error instanceof Error ? error.name : 'Unknown');
    console.error("[TRANSCRIPTS API] Error message:", error instanceof Error ? error.message : String(error));
    return NextResponse.json(
      { error: "Internal server error", details: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    );
  }
}

// PUT method to update existing transcript
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();

    if (!body.callId) {
      return NextResponse.json(
        { error: "Missing required field: callId" },
        { status: 400 }
      );
    }

    const callId = body.callId as Id<"calls">;
    const existingTranscript = await convex.query(api.tasks.getTranscriptByCall, { callId });

    if (!existingTranscript) {
      return NextResponse.json(
        { error: "Transcript not found" },
        { status: 404 }
      );
    }

    // Update transcript data
    const updateData: any = {};
    
    if (body.transcript) updateData.transcript = body.transcript;
    if (body.fullTranscript) updateData.fullTranscript = body.fullTranscript;
    if (body.language) updateData.language = body.language;
    if (body.duration !== undefined) updateData.duration = body.duration;

    // Note: You'll need to add an updateTranscript mutation to tasks.ts
    // For now, we'll return an error
    return NextResponse.json(
      { error: "Transcript updates not yet supported. Use DELETE and POST to replace." },
      { status: 501 }
    );

  } catch (error) {
    console.error("Error updating transcript:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

// DELETE method to remove transcript
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const callId = searchParams.get("callId");

    if (!callId) {
      return NextResponse.json(
        { error: "Missing callId parameter" },
        { status: 400 }
      );
    }

    const transcript = await convex.query(api.tasks.getTranscriptByCall, { 
      callId: callId as Id<"calls"> 
    });

    if (!transcript) {
      return NextResponse.json(
        { error: "Transcript not found" },
        { status: 404 }
      );
    }

    // Note: You'll need to add a deleteTranscript mutation to tasks.ts
    // For now, we'll return an error
    return NextResponse.json(
      { error: "Transcript deletion not yet supported" },
      { status: 501 }
    );

  } catch (error) {
    console.error("Error deleting transcript:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
